/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LeaseExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkLeaseStates"
      | "closeLease"
      | "confidentialProtocolId"
      | "createLease"
      | "getEncryptedLeaseTerms"
      | "getEncryptedStates"
      | "getLeaseCount"
      | "getLeaseInfo"
      | "getLesseeLeases"
      | "getLessorLeases"
      | "leaseCounter"
      | "leases"
      | "lesseeLeases"
      | "lessorLeases"
      | "updateLease"
      | "updateUsedValue"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LeaseClosed"
      | "LeaseCreated"
      | "LeaseExpired"
      | "LeaseRefundCalculated"
      | "LeaseUpdated"
      | "LeaseViolation"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkLeaseStates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeLease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createLease",
    values: [
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedLeaseTerms",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedStates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaseCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaseInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLesseeLeases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLessorLeases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "leaseCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "leases",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lesseeLeases",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lessorLeases",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLease",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUsedValue",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkLeaseStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closeLease", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedLeaseTerms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaseCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaseInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLesseeLeases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLessorLeases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leaseCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "leases", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lesseeLeases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lessorLeases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUsedValue",
    data: BytesLike
  ): Result;
}

export namespace LeaseClosedEvent {
  export type InputTuple = [
    leaseId: BigNumberish,
    closer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    leaseId: bigint,
    closer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    leaseId: bigint;
    closer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseCreatedEvent {
  export type InputTuple = [
    leaseId: BigNumberish,
    lessor: AddressLike,
    lessee: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    leaseId: bigint,
    lessor: string,
    lessee: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    leaseId: bigint;
    lessor: string;
    lessee: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseExpiredEvent {
  export type InputTuple = [leaseId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [leaseId: bigint, timestamp: bigint];
  export interface OutputObject {
    leaseId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseRefundCalculatedEvent {
  export type InputTuple = [leaseId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [leaseId: bigint, timestamp: bigint];
  export interface OutputObject {
    leaseId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseUpdatedEvent {
  export type InputTuple = [
    leaseId: BigNumberish,
    updater: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    leaseId: bigint,
    updater: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    leaseId: bigint;
    updater: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseViolationEvent {
  export type InputTuple = [leaseId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [leaseId: bigint, timestamp: bigint];
  export interface OutputObject {
    leaseId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LeaseExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): LeaseExecutor;
  waitForDeployment(): Promise<this>;

  interface: LeaseExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkLeaseStates: TypedContractMethod<
    [leaseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  closeLease: TypedContractMethod<
    [leaseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createLease: TypedContractMethod<
    [
      lessee: AddressLike,
      encryptedUsageCount: BytesLike,
      encryptedDaysLeft: BytesLike,
      encryptedPaymentStatus: BytesLike,
      encryptedAmountPaid: BytesLike,
      usageCountProof: BytesLike,
      daysLeftProof: BytesLike,
      paymentStatusProof: BytesLike,
      amountPaidProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getEncryptedLeaseTerms: TypedContractMethod<
    [leaseId: BigNumberish],
    [
      [string, string, string, string] & {
        encryptedUsageCount: string;
        encryptedDaysLeft: string;
        encryptedPaymentStatus: string;
        encryptedAmountPaid: string;
      }
    ],
    "view"
  >;

  getEncryptedStates: TypedContractMethod<
    [leaseId: BigNumberish],
    [
      [string, string, string] & {
        encryptedExpired: string;
        encryptedViolation: string;
        encryptedRefund: string;
      }
    ],
    "view"
  >;

  getLeaseCount: TypedContractMethod<[], [bigint], "view">;

  getLeaseInfo: TypedContractMethod<
    [leaseId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        id: bigint;
        lessor: string;
        lessee: string;
        createdAt: bigint;
        updatedAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getLesseeLeases: TypedContractMethod<
    [lessee: AddressLike],
    [bigint[]],
    "view"
  >;

  getLessorLeases: TypedContractMethod<
    [lessor: AddressLike],
    [bigint[]],
    "view"
  >;

  leaseCounter: TypedContractMethod<[], [bigint], "view">;

  leases: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ] & {
        id: bigint;
        lessor: string;
        lessee: string;
        createdAt: bigint;
        updatedAt: bigint;
        isActive: boolean;
        encryptedUsageCount: string;
        encryptedDaysLeft: string;
        encryptedPaymentStatus: string;
        encryptedAmountPaid: string;
        encryptedUsedValue: string;
        encryptedExpired: string;
        encryptedViolation: string;
        encryptedRefund: string;
      }
    ],
    "view"
  >;

  lesseeLeases: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  lessorLeases: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  updateLease: TypedContractMethod<
    [
      leaseId: BigNumberish,
      encryptedUsageCount: BytesLike,
      encryptedDaysLeft: BytesLike,
      encryptedPaymentStatus: BytesLike,
      usageCountProof: BytesLike,
      daysLeftProof: BytesLike,
      paymentStatusProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  updateUsedValue: TypedContractMethod<
    [
      leaseId: BigNumberish,
      encryptedUsedValue: BytesLike,
      usedValueProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkLeaseStates"
  ): TypedContractMethod<[leaseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closeLease"
  ): TypedContractMethod<[leaseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createLease"
  ): TypedContractMethod<
    [
      lessee: AddressLike,
      encryptedUsageCount: BytesLike,
      encryptedDaysLeft: BytesLike,
      encryptedPaymentStatus: BytesLike,
      encryptedAmountPaid: BytesLike,
      usageCountProof: BytesLike,
      daysLeftProof: BytesLike,
      paymentStatusProof: BytesLike,
      amountPaidProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedLeaseTerms"
  ): TypedContractMethod<
    [leaseId: BigNumberish],
    [
      [string, string, string, string] & {
        encryptedUsageCount: string;
        encryptedDaysLeft: string;
        encryptedPaymentStatus: string;
        encryptedAmountPaid: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedStates"
  ): TypedContractMethod<
    [leaseId: BigNumberish],
    [
      [string, string, string] & {
        encryptedExpired: string;
        encryptedViolation: string;
        encryptedRefund: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaseCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLeaseInfo"
  ): TypedContractMethod<
    [leaseId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        id: bigint;
        lessor: string;
        lessee: string;
        createdAt: bigint;
        updatedAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLesseeLeases"
  ): TypedContractMethod<[lessee: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLessorLeases"
  ): TypedContractMethod<[lessor: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "leaseCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "leases"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ] & {
        id: bigint;
        lessor: string;
        lessee: string;
        createdAt: bigint;
        updatedAt: bigint;
        isActive: boolean;
        encryptedUsageCount: string;
        encryptedDaysLeft: string;
        encryptedPaymentStatus: string;
        encryptedAmountPaid: string;
        encryptedUsedValue: string;
        encryptedExpired: string;
        encryptedViolation: string;
        encryptedRefund: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lesseeLeases"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lessorLeases"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateLease"
  ): TypedContractMethod<
    [
      leaseId: BigNumberish,
      encryptedUsageCount: BytesLike,
      encryptedDaysLeft: BytesLike,
      encryptedPaymentStatus: BytesLike,
      usageCountProof: BytesLike,
      daysLeftProof: BytesLike,
      paymentStatusProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateUsedValue"
  ): TypedContractMethod<
    [
      leaseId: BigNumberish,
      encryptedUsedValue: BytesLike,
      usedValueProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "LeaseClosed"
  ): TypedContractEvent<
    LeaseClosedEvent.InputTuple,
    LeaseClosedEvent.OutputTuple,
    LeaseClosedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseCreated"
  ): TypedContractEvent<
    LeaseCreatedEvent.InputTuple,
    LeaseCreatedEvent.OutputTuple,
    LeaseCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseExpired"
  ): TypedContractEvent<
    LeaseExpiredEvent.InputTuple,
    LeaseExpiredEvent.OutputTuple,
    LeaseExpiredEvent.OutputObject
  >;
  getEvent(
    key: "LeaseRefundCalculated"
  ): TypedContractEvent<
    LeaseRefundCalculatedEvent.InputTuple,
    LeaseRefundCalculatedEvent.OutputTuple,
    LeaseRefundCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseUpdated"
  ): TypedContractEvent<
    LeaseUpdatedEvent.InputTuple,
    LeaseUpdatedEvent.OutputTuple,
    LeaseUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseViolation"
  ): TypedContractEvent<
    LeaseViolationEvent.InputTuple,
    LeaseViolationEvent.OutputTuple,
    LeaseViolationEvent.OutputObject
  >;

  filters: {
    "LeaseClosed(uint256,address,uint256)": TypedContractEvent<
      LeaseClosedEvent.InputTuple,
      LeaseClosedEvent.OutputTuple,
      LeaseClosedEvent.OutputObject
    >;
    LeaseClosed: TypedContractEvent<
      LeaseClosedEvent.InputTuple,
      LeaseClosedEvent.OutputTuple,
      LeaseClosedEvent.OutputObject
    >;

    "LeaseCreated(uint256,address,address,uint256)": TypedContractEvent<
      LeaseCreatedEvent.InputTuple,
      LeaseCreatedEvent.OutputTuple,
      LeaseCreatedEvent.OutputObject
    >;
    LeaseCreated: TypedContractEvent<
      LeaseCreatedEvent.InputTuple,
      LeaseCreatedEvent.OutputTuple,
      LeaseCreatedEvent.OutputObject
    >;

    "LeaseExpired(uint256,uint256)": TypedContractEvent<
      LeaseExpiredEvent.InputTuple,
      LeaseExpiredEvent.OutputTuple,
      LeaseExpiredEvent.OutputObject
    >;
    LeaseExpired: TypedContractEvent<
      LeaseExpiredEvent.InputTuple,
      LeaseExpiredEvent.OutputTuple,
      LeaseExpiredEvent.OutputObject
    >;

    "LeaseRefundCalculated(uint256,uint256)": TypedContractEvent<
      LeaseRefundCalculatedEvent.InputTuple,
      LeaseRefundCalculatedEvent.OutputTuple,
      LeaseRefundCalculatedEvent.OutputObject
    >;
    LeaseRefundCalculated: TypedContractEvent<
      LeaseRefundCalculatedEvent.InputTuple,
      LeaseRefundCalculatedEvent.OutputTuple,
      LeaseRefundCalculatedEvent.OutputObject
    >;

    "LeaseUpdated(uint256,address,uint256)": TypedContractEvent<
      LeaseUpdatedEvent.InputTuple,
      LeaseUpdatedEvent.OutputTuple,
      LeaseUpdatedEvent.OutputObject
    >;
    LeaseUpdated: TypedContractEvent<
      LeaseUpdatedEvent.InputTuple,
      LeaseUpdatedEvent.OutputTuple,
      LeaseUpdatedEvent.OutputObject
    >;

    "LeaseViolation(uint256,uint256)": TypedContractEvent<
      LeaseViolationEvent.InputTuple,
      LeaseViolationEvent.OutputTuple,
      LeaseViolationEvent.OutputObject
    >;
    LeaseViolation: TypedContractEvent<
      LeaseViolationEvent.InputTuple,
      LeaseViolationEvent.OutputTuple,
      LeaseViolationEvent.OutputObject
    >;
  };
}
